# Generated by Django 3.2.13 on 2022-07-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursenumber', models.IntegerField(db_column='CourseNumber')),
                ('coursetitle', models.TextField(blank=True, db_column='CourseTitle', null=True)),
                ('sections', models.TextField(blank=True, db_column='Sections', null=True)),
                ('day', models.TextField(blank=True, db_column='Day', null=True)),
                ('time', models.TextField(blank=True, db_column='Time', null=True)),
                ('sectioncapacity', models.IntegerField(blank=True, db_column='SectionCapacity', null=True)),
                ('studentregistered', models.IntegerField(blank=True, db_column='StudentRegistered', null=True)),
            ],
            options={
                'db_table': 'Classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('collegeid', models.AutoField(db_column='CollegeID', primary_key=True, serialize=False)),
                ('collegename', models.TextField(blank=True, db_column='CollegeName', null=True)),
            ],
            options={
                'db_table': 'College',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CsCourses',
            fields=[
                ('courseid', models.AutoField(db_column='CourseID', primary_key=True, serialize=False)),
                ('coursename', models.TextField(blank=True, db_column='CourseName', null=True)),
                ('hours', models.IntegerField(blank=True, db_column='Hours', null=True)),
                ('prerequisite', models.TextField(blank=True, db_column='Prerequisite', null=True)),
                ('coursetype', models.TextField(blank=True, db_column='CourseType', null=True)),
            ],
            options={
                'db_table': 'CS_Courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stdid', models.AutoField(db_column='StdID', primary_key=True, serialize=False)),
                ('stdname', models.TextField(blank=True, db_column='StdName', null=True)),
                ('stdmajor', models.TextField(blank=True, db_column='StdMajor', null=True)),
                ('gpa', models.TextField(blank=True, db_column='GPA', null=True)),
                ('hoursfinished', models.IntegerField(blank=True, db_column='HoursFinished', null=True)),
                ('coursesfinished', models.TextField(blank=True, db_column='CoursesFinished', null=True)),
            ],
            options={
                'db_table': 'Student',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
